lib/plausible_web/plugins/api/router.ex
defmodule PlausibleWeb.Plugins.API.Router do
  use PlausibleWeb, :router

  pipeline :auth do
    plug(PlausibleWeb.Plugs.AuthorizePluginsAPI)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(OpenApiSpex.Plug.PutApiSpec, module: PlausibleWeb.Plugins.API.Spec)
  end

  scope "/spec" do
    pipe_through(:api)
    get("/openapi", OpenApiSpex.Plug.RenderSpec, [])
    get("/swagger-ui", OpenApiSpex.Plug.SwaggerUI, path: "/api/plugins/spec/openapi")
  end

  scope "/v1", PlausibleWeb.Plugins.API.Controllers do
    pipe_through([:api, :auth])

    get("/shared_links", SharedLinks, :index)
    get("/shared_links/:id", SharedLinks, :get)
    put("/shared_links", SharedLinks, :create)

    get("/goals", Goals, :index)
    get("/goals/:id", Goals, :get)
    put("/goals", Goals, :create)

    delete("/goals/:id", Goals, :delete)
    delete("/goals", Goals, :delete_bulk)

    put("/custom_props", CustomProps, :enable)
    delete("/custom_props", CustomProps, :disable)
  end
end

lib/plausible_web/router.ex
defmodule PlausibleWeb.Router do
  use PlausibleWeb, :router
  use Plausible
  import Phoenix.LiveView.Router
  @two_weeks_in_seconds 60 * 60 * 24 * 14

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_secure_browser_headers
    plug PlausibleWeb.Plugs.NoRobots
    on_full_build(do: nil, else: plug(PlausibleWeb.FirstLaunchPlug, redirect_to: "/register"))
    plug PlausibleWeb.SessionTimeoutPlug, timeout_after_seconds: @two_weeks_in_seconds
    plug PlausibleWeb.AuthPlug
    plug PlausibleWeb.LastSeenPlug
  end

  pipeline :shared_link do
    plug :accepts, ["html"]
    plug :put_secure_browser_headers
    plug PlausibleWeb.Plugs.NoRobots
  end

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :focus_layout do
    plug :put_root_layout, html: {PlausibleWeb.LayoutView, :focus}
  end

  pipeline :app_layout do
    plug :put_root_layout, html: {PlausibleWeb.LayoutView, :app}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug PlausibleWeb.AuthPlug
  end

  pipeline :internal_stats_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug PlausibleWeb.AuthorizeSiteAccess
    plug PlausibleWeb.Plugs.NoRobots
  end

  pipeline :public_api do
    plug :accepts, ["json"]
  end

  on_full_build do
    pipeline :flags do
      plug :accepts, ["html"]
      plug :put_secure_browser_headers
      plug PlausibleWeb.Plugs.NoRobots
      plug :fetch_session

      plug PlausibleWeb.CRMAuthPlug
    end
  end

  if Mix.env() == :dev do
    forward "/sent-emails", Bamboo.SentEmailViewerPlug
  end

  on_full_build do
    use Kaffy.Routes,
      scope: "/crm",
      pipe_through: [PlausibleWeb.Plugs.NoRobots, PlausibleWeb.CRMAuthPlug]
  end

  on_full_build do
    scope "/crm", PlausibleWeb do
      pipe_through :flags
      get "/auth/user/:user_id/usage", AdminController, :usage
    end
  end

  on_full_build do
    scope path: "/flags" do
      pipe_through :flags
      forward "/", FunWithFlags.UI.Router, namespace: "flags"
    end
  end

  scope path: "/api/plugins" do
    forward "/", PlausibleWeb.Plugins.API.Router
  end

  scope "/api/stats", PlausibleWeb.Api do
    pipe_through :internal_stats_api

    on_full_build do
      get "/:domain/funnels/:id", StatsController, :funnel
    end

    get "/:domain/current-visitors", StatsController, :current_visitors
    get "/:domain/main-graph", StatsController, :main_graph
    get "/:domain/top-stats", StatsController, :top_stats
    get "/:domain/sources", StatsController, :sources
    get "/:domain/utm_mediums", StatsController, :utm_mediums
    get "/:domain/utm_sources", StatsController, :utm_sources
    get "/:domain/utm_campaigns", StatsController, :utm_campaigns
    get "/:domain/utm_contents", StatsController, :utm_contents
    get "/:domain/utm_terms", StatsController, :utm_terms
    get "/:domain/referrers/:referrer", StatsController, :referrer_drilldown
    get "/:domain/pages", StatsController, :pages
    get "/:domain/entry-pages", StatsController, :entry_pages
    get "/:domain/exit-pages", StatsController, :exit_pages
    get "/:domain/countries", StatsController, :countries
    get "/:domain/regions", StatsController, :regions
    get "/:domain/cities", StatsController, :cities
    get "/:domain/browsers", StatsController, :browsers
    get "/:domain/browser-versions", StatsController, :browser_versions
    get "/:domain/operating-systems", StatsController, :operating_systems
    get "/:domain/operating-system-versions", StatsController, :operating_system_versions
    get "/:domain/screen-sizes", StatsController, :screen_sizes
    get "/:domain/conversions", StatsController, :conversions
    get "/:domain/custom-prop-values/:prop_key", StatsController, :custom_prop_values
    get "/:domain/suggestions/:filter_name", StatsController, :filter_suggestions
  end

  scope "/api/v1/stats", PlausibleWeb.Api do
    pipe_through [:public_api, PlausibleWeb.AuthorizeStatsApiPlug]

    get "/realtime/visitors", ExternalStatsController, :realtime_visitors
    get "/aggregate", ExternalStatsController, :aggregate
    get "/breakdown", ExternalStatsController, :breakdown
    get "/timeseries", ExternalStatsController, :timeseries
  end

  on_full_build do
    scope "/api/v1/sites", PlausibleWeb.Api do
      pipe_through [:public_api, PlausibleWeb.AuthorizeSitesApiPlug]

      post "/", ExternalSitesController, :create_site
      put "/shared-links", ExternalSitesController, :find_or_create_shared_link
      put "/goals", ExternalSitesController, :find_or_create_goal
      delete "/goals/:goal_id", ExternalSitesController, :delete_goal
      get "/:site_id", ExternalSitesController, :get_site
      put "/:site_id", ExternalSitesController, :update_site
      delete "/:site_id", ExternalSitesController, :delete_site
    end
  end

  scope "/api", PlausibleWeb do
    pipe_through :api

    post "/event", Api.ExternalController, :event
    get "/error", Api.ExternalController, :error
    get "/health", Api.ExternalController, :health
    get "/system", Api.ExternalController, :info

    post "/paddle/webhook", Api.PaddleController, :webhook

    get "/:domain/status", Api.InternalController, :domain_status
    put "/:domain/disable-feature", Api.InternalController, :disable_feature

    get "/sites", Api.InternalController, :sites
  end

  scope "/", PlausibleWeb do
    pipe_through [:browser, :csrf]

    scope alias: Live, assigns: %{connect_live_socket: true} do
      pipe_through [PlausibleWeb.RequireLoggedOutPlug, :focus_layout]

      scope assigns: %{disable_registration_for: [:invite_only, true]} do
        pipe_through PlausibleWeb.Plugs.MaybeDisableRegistration

        live "/register", RegisterForm, :register_form, as: :auth
      end

      scope assigns: %{
              disable_registration_for: true,
              dogfood_page_path: "/register/invitation/:invitation_id"
            } do
        pipe_through PlausibleWeb.Plugs.MaybeDisableRegistration

        live "/register/invitation/:invitation_id", RegisterForm, :register_from_invitation_form,
          as: :auth
      end
    end

    post "/register", AuthController, :register
    post "/register/invitation/:invitation_id", AuthController, :register_from_invitation
    get "/activate", AuthController, :activate_form
    post "/activate/request-code", AuthController, :request_activation_code
    post "/activate", AuthController, :activate
    get "/login", AuthController, :login_form
    post "/login", AuthController, :login
    get "/password/request-reset", AuthController, :password_reset_request_form
    post "/password/request-reset", AuthController, :password_reset_request
    post "/2fa/setup/initiate", AuthController, :initiate_2fa_setup
    get "/2fa/setup/verify", AuthController, :verify_2fa_setup_form
    post "/2fa/setup/verify", AuthController, :verify_2fa_setup
    post "/2fa/disable", AuthController, :disable_2fa
    post "/2fa/recovery_codes", AuthController, :generate_2fa_recovery_codes
    get "/2fa/verify", AuthController, :verify_2fa_form
    post "/2fa/verify", AuthController, :verify_2fa
    get "/2fa/use_recovery_code", AuthController, :verify_2fa_recovery_code_form
    post "/2fa/use_recovery_code", AuthController, :verify_2fa_recovery_code
    get "/password/reset", AuthController, :password_reset_form
    post "/password/reset", AuthController, :password_reset
    get "/avatar/:hash", AvatarController, :avatar
    post "/error_report", ErrorReportController, :submit_error_report
  end

  scope "/", PlausibleWeb do
    pipe_through [:shared_link]

    get "/share/:domain", StatsController, :shared_link
    post "/share/:slug/authenticate", StatsController, :authenticate_shared_link
  end

  scope "/", PlausibleWeb do
    pipe_through [:browser, :csrf]

    get "/logout", AuthController, :logout
    get "/settings", AuthController, :user_settings
    put "/settings", AuthController, :save_settings
    put "/settings/email", AuthController, :update_email
    post "/settings/email/cancel", AuthController, :cancel_update_email
    delete "/me", AuthController, :delete_me
    get "/settings/api-keys/new", AuthController, :new_api_key
    post "/settings/api-keys", AuthController, :create_api_key
    delete "/settings/api-keys/:id", AuthController, :delete_api_key

    get "/auth/google/callback", AuthController, :google_auth_callback

    get "/", PageController, :index

    get "/billing/change-plan/preview/:plan_id", BillingController, :change_plan_preview
    post "/billing/change-plan/:new_plan_id", BillingController, :change_plan
    get "/billing/choose-plan", BillingController, :choose_plan
    get "/billing/upgrade-to-enterprise-plan", BillingController, :upgrade_to_enterprise_plan
    get "/billing/upgrade-success", BillingController, :upgrade_success
    get "/billing/subscription/ping", BillingController, :ping_subscription

    scope alias: Live, assigns: %{connect_live_socket: true} do
      pipe_through [:app_layout, PlausibleWeb.RequireAccountPlug]

      live "/sites", Sites, :index, as: :site
    end

    get "/sites/new", SiteController, :new
    post "/sites", SiteController, :create_site
    get "/sites/:website/change-domain", SiteController, :change_domain
    put "/sites/:website/change-domain", SiteController, :change_domain_submit
    get "/:website/change-domain-snippet", SiteController, :add_snippet_after_domain_change
    post "/sites/:website/make-public", SiteController, :make_public
    post "/sites/:website/make-private", SiteController, :make_private
    post "/sites/:website/weekly-report/enable", SiteController, :enable_weekly_report
    post "/sites/:website/weekly-report/disable", SiteController, :disable_weekly_report
    post "/sites/:website/weekly-report/recipients", SiteController, :add_weekly_report_recipient

    delete "/sites/:website/weekly-report/recipients/:recipient",
           SiteController,

lib/plausible/imported/site.ex
defmodule Plausible.Imported do
  @tables ~w(
    imported_visitors imported_sources imported_pages imported_entry_pages
    imported_exit_pages imported_locations imported_devices imported_browsers
    imported_operating_systems
  )
  @spec tables() :: [String.t()]
  def tables, do: @tables

  def forget(site) do
    Plausible.Purge.delete_imported_stats!(site)
  end
end

lib/plausible/site/admin.ex
defmodule Plausible.SiteAdmin do
  use Plausible.Repo
  import Ecto.Query

  def ordering(_schema) do
    [desc: :inserted_at]
  end

  def search_fields(_schema) do
    [
      :domain,
      members: [:name, :email]
    ]
  end

  def custom_index_query(_conn, _schema, query) do
    from(r in query,
      inner_join: o in assoc(r, :owner),
      inner_join: m in assoc(r, :memberships),
      preload: [owner: o, memberships: {m, :user}]
    )
  end

  def form_fields(_) do
    [
      domain: %{update: :readonly},
      timezone: %{choices: Plausible.Timezones.options()},
      public: nil,
      stats_start_date: nil,
      ingest_rate_limit_scale_seconds: %{
        help_text: "Time scale for which events rate-limiting is calculated. Default: 60"
      },
      ingest_rate_limit_threshold: %{
        help_text:
          "Keep empty to disable rate limiting, set to 0 to bar all events. Any positive number sets the limit."
      }
    ]
  end

  def index(_) do
    [
      domain: nil,
      inserted_at: %{name: "Created at", value: &format_date(&1.inserted_at)},
      timezone: nil,
      public: nil,
      owner: %{value: &get_owner/1},
      other_members: %{value: &get_other_members/1},
      limits: %{
        value: fn site ->
          rate_limiting_status =
            case site.ingest_rate_limit_threshold do
              nil -> ""
              0 -> "🛑 BLOCKED"
              n -> "⏱ #{n}/#{site.ingest_rate_limit_scale_seconds}s (per server)"
            end

          owner = site.owner

          owner_limits =
            if owner.accept_traffic_until &&
                 Date.after?(Date.utc_today(), owner.accept_traffic_until) do
              "💸 Rejecting traffic"
            end

          {:safe, Enum.join([rate_limiting_status, owner_limits], "<br/><br/>")}
        end
      }
    ]
  end

  def list_actions(_conn) do
    [
      transfer_ownership: %{
        name: "Transfer ownership",
        inputs: [
          %{name: "email", title: "New Owner Email", default: nil}
        ],
        action: fn conn, sites, params -> transfer_ownership(conn, sites, params) end
      },
      transfer_ownership_direct: %{
        name: "Transfer ownership without invite",
        inputs: [
          %{name: "email", title: "New Owner Email", default: nil}
        ],
        action: fn conn, sites, params -> transfer_ownership_direct(conn, sites, params) end
      }
    ]
  end

  defp transfer_ownership(_conn, [], _params) do
    {:error, "Please select at least one site from the list"}
  end

  defp transfer_ownership(conn, sites, %{"email" => email}) do
    new_owner = Plausible.Auth.find_user_by(email: email)
    inviter = conn.assigns[:current_user]

    if new_owner do
      result =
        Plausible.Site.Memberships.bulk_create_invitation(
          sites,
          inviter,
          new_owner.email,
          :owner,
          check_permissions: false
        )

      case result do
        {:ok, _} ->
          :ok

        {:error, :transfer_to_self} ->
          {:error, "User is already an owner of one of the sites"}
      end
    else
      {:error, "User could not be found"}
    end
  end

  defp transfer_ownership_direct(_conn, [], _params) do
    {:error, "Please select at least one site from the list"}
  end

  defp transfer_ownership_direct(_conn, sites, %{"email" => email}) do
    new_owner = Plausible.Auth.find_user_by(email: email)

    if new_owner do
      case Plausible.Site.Memberships.bulk_transfer_ownership_direct(sites, new_owner) do
        {:ok, _} ->
          :ok

        {:error, :transfer_to_self} ->
          {:error, "User is already an owner of one of the sites"}

        {:error, :no_plan} ->
          {:error, "The new owner does not have a subscription"}

        {:error, {:over_plan_limits, limits}} ->
          {:error, "Plan limits exceeded for one of the sites: #{Enum.join(limits, ", ")}"}
      end
    else
      {:error, "User could not be found"}
    end
  end

  defp format_date(date) do
    Timex.format!(date, "{Mshort} {D}, {YYYY}")
  end

  defp get_owner(site) do
    owner = site.owner

    if owner do
      {:safe,
       """
        <a href="/crm/auth/user/#{owner.id}">#{owner.name}</a>
        <br/><br/>
        #{owner.email}
       """}
    end
  end

  defp get_other_members(site) do
    Enum.filter(site.memberships, &(&1.role != :owner))
    |> Enum.map(fn m -> m.user.email <> "(#{to_string(m.role)})" end)
    |> Enum.join(", ")
  end

  def get_struct_fields(module) do
    module.__struct__()
    |> Map.drop([:__meta__, :__struct__])
    |> Map.keys()
    |> Enum.map(&Atom.to_string/1)
    |> Enum.sort()
  end

  def create_changeset(schema, attrs), do: Plausible.Site.crm_changeset(schema, attrs)
  def update_changeset(schema, attrs), do: Plausible.Site.crm_changeset(schema, attrs)
end

lib/plausible/site/google_auth.ex
defmodule Plausible.Site.GoogleAuth do
  use Ecto.Schema
  import Ecto.Changeset

  schema "google_auth" do
    field :email, :string
    field :property, :string
    field :refresh_token, :string
    field :access_token, :string
    field :expires, :naive_datetime

    belongs_to :user, Plausible.Auth.User
    belongs_to :site, Plausible.Site

    timestamps()
  end

  def changeset(auth, attrs \\ %{}) do
    auth
    |> cast(attrs, [:refresh_token, :access_token, :expires, :email, :user_id, :site_id])
    |> validate_required([:refresh_token, :access_token, :expires, :email, :user_id, :site_id])
    |> unique_constraint(:site)
  end

  def set_property(auth, attrs \\ %{}) do
    auth
    |> cast(attrs, [:property])
  end
end

lib/plausible/site/imported_data.ex
defmodule Plausible.Site.ImportedData do
  @moduledoc """
  Embedded schema for analytics imports
  """
  use Ecto.Schema

  embedded_schema do
    field :start_date, :date
    field :end_date, :date
    field :source, :string
    field :status, :string
  end
end

lib/plausible/site/memberships/remove_invitation.ex
defmodule Plausible.Site.Memberships.RemoveInvitation do
  @moduledoc """
  Service for removing invitations.
  """

  alias Plausible.Auth
  alias Plausible.Site.Memberships.Invitations

  @spec remove_invitation(String.t(), Plausible.Site.t()) ::
          {:ok, Auth.Invitation.t()} | {:error, :invitation_not_found}
  def remove_invitation(invitation_id, site) do
    with {:ok, invitation} <- Invitations.find_for_site(invitation_id, site) do
      Invitations.delete_invitation(invitation)

      {:ok, invitation}
    end
  end
end

lib/plausible_web/templates/site/edit_shared_link.html.eex
<%= form_for @changeset, "/sites/#{URI.encode_www_form(@site.domain)}/shared-links/#{@changeset.data.slug}", [class: "max-w-md w-full mx-auto bg-white dark:bg-gray-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 mt-8"], fn f -> %>
  <h2 class="text-xl font-black dark:text-gray-100">Edit shared link</h2>
  <div class="my-4">
    <%= label f, :name, "Name", class: "block text-sm font-medium text-gray-700 dark:text-gray-100" %>
    <div class="mt-1">
      <%= text_input f, :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md", required: "required" %>
      <%= error_tag f, :name %>
    </div>
  </div>

  <%= submit "Update", class: "button mt-4 w-full" %>
<% end %>

lib/plausible_web/templates/site/import_from_google_confirm.html.eex
<%= form_for @conn, Routes.site_path(@conn, :import_from_google, @site.domain), [class: "max-w-md w-full mx-auto bg-white dark:bg-gray-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 mt-8"], fn f -> %>
  <h2 class="text-xl font-black dark:text-gray-100">Import from Google Analytics</h2>

  <%= hidden_input(f, :access_token, value: @access_token) %>
  <%= hidden_input(f, :refresh_token, value: @refresh_token) %>
  <%= hidden_input(f, :expires_at, value: @expires_at) %>

  <%= case @start_date do %>
    <% {:ok, start_date} -> %>

      <div class="mt-6 text-sm text-gray-500 dark:text-gray-200">
        Stats from this property and time period will be imported from your Google Analytics account to your Plausible dashboard
      </div>

      <div class="mt-6">
        <%= styled_label(f, :view_id, "Google Analytics view") %>
        <span class="block w-full text-base dark:text-gray-100 sm:text-sm dark:bg-gray-800"><%= @selected_view_id_name %></span>
        <%= hidden_input f, :view_id, readonly: "true", value: @selected_view_id %>
      </div>
      <div class="flex justify-between mt-3">
        <div class="w-36">
          <%= styled_label f, :start_date, "From"  %>
          <span class="block w-full text-base dark:text-gray-100 sm:text-sm dark:bg-gray-800"><%= PlausibleWeb.EmailView.date_format(start_date) %></span>
          <%= hidden_input f, :start_date, value: start_date, readonly: "true" %>
        </div>
        <div class="align-middle pt-4 dark:text-gray-100">&rarr;</div>
        <div class="w-36">
          <%= styled_label f, :end_date, "To"  %>
          <span class="block w-full text-base dark:text-gray-100 sm:text-sm dark:bg-gray-800"><%= PlausibleWeb.EmailView.date_format(@end_date) %></span>
          <%= hidden_input f, :end_date, value: @end_date, readonly: "true" %>
        </div>
      </div>
    <% {:error, error} -> %>
      <p class="text-gray-700 dark:text-gray-300 mt-6">The following error occurred when fetching your Google Analytics data.</p>
      <p class="text-red-700 font-medium mt-3"><%= error %></p>
    <% end %>

  <%= submit "Confirm import", class: "button mt-6" %>
<% end %>

lib/plausible_web/templates/site/import_from_google_user_metric_form.html.eex
<div class="max-w-md w-full mx-auto bg-white dark:bg-gray-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 mt-8">
  <h2 class="text-xl font-black dark:text-gray-100">Import from Google Analytics</h2>

  <div class="mt-6 text-sm text-gray-500 dark:text-gray-200">
    <p>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 inline text-orange-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
    </svg>

    Important: Since your GA property includes data from before 23rd August 2016, you have to take an extra step to make sure we can import data smoothly.
    </p>

    <ol class="mt-4">
      <li>1. Navigate to the GA property you want to import from</li>
      <li>2. Go to Admin &gt; Property Settings &gt; User Analysis</li>
      <li>3. Make sure <i>Enable Users Metric in Reporting</i> is <b>OFF</b></li>
    </ol>

    <p class="mt-4">
    The setting may take a few minutes to take effect. If your imported data is showing 0 visitors in unexpected places, it's probably caused by this and you
    can try importing again later.
    </p>
  </div>

  <%= link("Continue ->", to: Routes.site_path(@conn, :import_from_google_confirm, @site.domain, view_id: @view_id, access_token: @access_token, refresh_token: @refresh_token, expires_at: @expires_at), class: "button mt-6") %>
</div>

lib/plausible_web/templates/site/import_from_google_view_id_form.html.eex
<%= form_for @conn, Routes.site_path(@conn, :import_from_google_view_id, @site.domain), [class: "max-w-md w-full mx-auto bg-white dark:bg-gray-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 mt-8"], fn f -> %>
  <h2 class="text-xl font-black dark:text-gray-100">Import from Google Analytics</h2>

  <%= hidden_input(f, :access_token, value: @access_token) %>
  <%= hidden_input(f, :refresh_token, value: @refresh_token) %>
  <%= hidden_input(f, :expires_at, value: @expires_at) %>

  <div class="mt-6 text-sm text-gray-500 dark:text-gray-200">
    Choose the view in your Google Analytics account that will be imported to the <%= @site.domain %> dashboard.
  </div>

  <div class="mt-3">
    <%= styled_label(f, :view_id, "Google Analytics view") %>
    <%= styled_select f, :view_id, @view_ids, prompt: "(Choose view)", required: "true" %>
    <%= styled_error(@conn.assigns[:selected_view_id_error]) %>
  </div>

  <%= submit "Continue ->", class: "button mt-6" %>
<% end %>

lib/plausible_web/templates/site/new_shared_link.html.eex
<%= form_for @changeset, "/sites/#{URI.encode_www_form(@site.domain)}/shared-links", [class: "max-w-md w-full mx-auto bg-white dark:bg-gray-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 mt-8"], fn f -> %>
  <h2 class="text-xl font-black dark:text-gray-100">New shared link</h2>
  <div class="my-4">
    <%= label f, :name, "Name", class: "block text-sm font-medium text-gray-700 dark:text-gray-300" %>
    <div class="mt-1">
      <%= text_input f, :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md dark:bg-gray-900 dark:border-gray-500 dark:text-gray-300 dark:focus:bg-gray-800 dark:focus:border-gray-500", required: "required", autocomplete: "off" %>
      <%= error_tag f, :name %>
    </div>
  </div>
  <div class="my-4">
    <%= label f, :password, "Password (optional)", class: "block text-sm font-medium text-gray-700 dark:text-gray-300" %>
    <div class="mt-1">
      <%= password_input f, :password, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md dark:bg-gray-900 dark:border-gray-500 dark:text-gray-300 dark:focus:bg-gray-800 dark:focus:border-gray-500", autocomplete: "new-password" %>
      <%= error_tag f, :password %>
      <p class="mt-2 text-sm text-gray-500 dark:text-gray-200">
        Password protection is optional. Please make sure you save it in a secure place. Once the link is created, we cannot reveal the password.
      </p>
    </div>
  </div>

  <%= submit "Create shared link", class: "button mt-4 w-full" %>
<% end %>

lib/plausible_web/templates/site/settings_integrations.html.heex
<PlausibleWeb.Components.Settings.settings_search_console
  site={@site}
  search_console_domains={@search_console_domains}
/>
<PlausibleWeb.Components.Settings.settings_google_import
  site={@site}
  imported_pageviews={@imported_pageviews}
/>

<section
  :if={@has_plugins_tokens? || @conn.query_params["new_token"]}
  class="shadow bg-white dark:bg-gray-800 sm:rounded-md sm:overflow-hidden"
>
  <div class="py-6 px-4 sm:p-6">
    <header class="relative">
      <h2 class="text-lg leading-6 font-medium text-gray-900 dark:text-gray-100">
        Plugins API Tokens
      </h2>
      <p class="mt-1 text-sm leading-5 text-gray-500 dark:text-gray-200">
        Control Plugins API Access
      </p>
    </header>

    <%= live_render(@conn, PlausibleWeb.Live.Plugins.API.Settings,
      session: %{
        "site_id" => @site.id,
        "domain" => @site.domain,
        "new_token" => @conn.query_params["new_token"]
      }
    ) %>
  </div>
</section>